### ISSUE TITLE
Unable to generate a URL for the named route "login" as such route does not exist.

### ISSUE THREAD

**Issue by luislaborda** [ldaptools/ldaptools-bundle#11]
I'm trying to implement ldaptools-bundle with FOSUserBundle, I believe everything is ok, However I'm running into the problem that when submitting the form, I get the following error:

Unable to generate a URL for the named route "login" as such route does not exist.
500 Internal Server Error - RouteNotFoundException

in vendor\ldaptools\ldaptools-bundle\Security\LdapGuardAuthenticator.php at line 203
at Router ->generate ('login') 

This is the list of my routes:

 ----------------------------------- ---------- -------- ------ -----------------------------------
  Name                                Method     Scheme   Host   Path
 ----------------------------------- ---------- -------- ------ -----------------------------------
  _wdt                                ANY        ANY      ANY    /_wdt/{token}
  _profiler_home               ANY        ANY      ANY    /_profiler/
  _profiler_search              ANY        ANY      ANY    /_profiler/search
  _profiler_search_bar       ANY        ANY      ANY    /_profiler/search_bar
  _profiler_info                 ANY        ANY      ANY    /_profiler/info/{about}
  _profiler_phpinfo           ANY        ANY      ANY    /_profiler/phpinfo
  _profiler_search_results ANY        ANY      ANY    /_profiler/{token}/search/results
  _profiler_open_file         ANY        ANY      ANY    /_profiler/open
  _profiler                         ANY        ANY      ANY    /_profiler/{token}
  _profiler_router             ANY        ANY      ANY    /_profiler/{token}/router
  _profiler_exception       ANY        ANY      ANY    /_profiler/{token}/exception
  _profiler_exception_css ANY        ANY      ANY    /_profiler/{token}/exception.css
  _twig_error_test            ANY        ANY      ANY    /_error/{code}.{_format}
  admin_default_index    ANY        ANY      ANY    /admin/
  security_login                ANY        ANY      ANY    /admin/login
  homepage                    ANY        ANY      ANY    /
  fos_user_security_login              GET|POST   ANY      ANY    /login
  fos_user_security_check             POST       ANY      ANY    /login_check
  fos_user_security_logout            GET|POST   ANY      ANY    /logout
  fos_user_profile_show                GET        ANY      ANY    /profile/
  fos_user_profile_edit                  GET|POST   ANY      ANY    /profile/edit
  fos_user_registration_register      GET|POST   ANY      ANY    /register/
  fos_user_registration_check_email   GET        ANY      ANY    /register/check-email
  fos_user_registration_confirm       GET        ANY      ANY    /register/confirm/{token}
  fos_user_registration_confirmed   GET        ANY      ANY    /register/confirmed
  fos_user_resetting_request            GET        ANY      ANY    /resetting/request
  fos_user_resetting_send_email       POST       ANY      ANY    /resetting/send-email
  fos_user_resetting_check_email      GET        ANY      ANY    /resetting/check-email
  fos_user_resetting_reset                 GET|POST   ANY      ANY    /resetting/reset/{token}
  fos_user_change_password            GET|POST   ANY      ANY    /profile/change-password

```
routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

```
security.yml
        admin:
            anonymous: ~
            # Use the default LDAP user provider defined above
            # provider: ldap
            provider: fos_userbundle
            form_login:
                login_path: login
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
                use_forward: true
                default_target_path: default_security_target
                failure_path: login_failure
            pattern: ^/
            logout: ~
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
        login:
            pattern: ^/login$
            anonymous: ~
```

Any suggestions on how to fix this issue?

**Comment by ChadSikorra** [comment]
It assumes your default login route is called `login`. You can change it:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Configuration-Reference.md#start_path

```yaml
ldap_tools:
    security:
        guard:
            start_path: 'fos_user_security_login'
````

Or define your own route called 'login' that maps to '/login' so you're not dependent on that fosuser one.
