### ISSUE TITLE
Custom username attribute

### ISSUE THREAD

**Issue by quentinus95** [ldaptools/ldaptools-bundle#14]
Hello,

Thanks for your awesome bundle.

I don't have a `username` attribute in my users ldap entries; is there a clean way without extending the default user provider (because it is actually the only thing I need to change) to customize the hardcoded attribute in the `loadUserByUsername` method of the `LdapUserProvider` to use "uid" attribute instead?

Thanks!

**Comment by ChadSikorra** [comment]
Basically what you have to do is extend the LdapTools schema file and overwrite the mapping for the `username` attribute. These are the general steps:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#mapping-ldap-attributes

If you're using OpenLDAP then your step # 2 would look something like this:

```yaml
# Extends the default 'openldap' schema for LdapTools
extends_default: openldap
objects:
    # Create a special 'LoginUser' type extending the default...
    login_user:
        extends_default: [ 'openldap', 'user' ]
        type: 'SymfonyUser'
        attributes:
            username: uid
```
