### ISSUE TITLE
How to bind username with the user's inputs ?

### ISSUE THREAD

**Issue by younessadmi** [ldaptools/ldaptools-bundle#17]
Hello,

First, i'd like to thank for this bundle. LDAP Authentication is killing my mind since long time.

Is it possible to avoid to provide the `ldap_tools.domains.example.username`  in `app/config/config.yml` ?

I want the user to provide his own username and password to bind the ldap server

**Comment by younessadmi** [comment]
Hi there,

I finally found a solution randomly. By leaving the username and password empty, it works ! :+1: 

```
ldap_tools:
    domains:
        company:
            domain_name: vnet.company.com
            username: 
            password: 
            base_dn: "dc=vnet,dc=company,dc=com"
            servers: ['ldap01.vnet.company.com']
```
