### ISSUE TITLE
Invalid DN syntax when trying to connect

### ISSUE THREAD

**Issue by tomapp** [ldaptools/ldaptools-bundle#19]
Hi,

I have an issue with my OpenLDAP. I go "Invalid DN syntax" when the second parameter of the ldap_bind function is setted to "admin@origin.org". ldap_bind works with this syntax: "cn=admin,dc=origin,dc=org".

This is my config :
```yaml
ldap_tools:
    domains:
        main:
            domain_name: origin.org
            base_dn: dc=origin,dc=org
            username: admin
            password: admin
            servers: [ldap]
```

Thank's you for help ! :)

**Comment by ChadSikorra** [comment]
Hi Thomas! I think what you want to do is set the `username` parameter to the full DN (ie. `cn=admin,dc=origin,dc=org`). Also you will probably want to set the `ldap_type` parameter to `openldap`.

So it would be like:

```yaml
ldap_tools:
    domains:
        main:
            domain_name: origin.org
            base_dn: dc=origin,dc=org
            username: cn=admin,dc=origin,dc=org
            password: admin
            servers: [ldap]
            ldap_type: openldap
```

A username only bind only works in Active Directory (which accepts many different unique values for a valid username). In OpenLDAP it requires a full DN to bind. Let me know if you still run into issues.
