### ISSUE TITLE
User Roles not Filtering on Symfony

### ISSUE THREAD

**Issue by fabsnvs** [ldaptools/ldaptools-bundle#2]
Hello Symfony users,
I installed LdapToolsBundle in my symfony 3.1 project, and at the beggining it worked nice. But, when I was required to set security roles using filters I got big confused how this tool works. I am using the following configuration, and I set CN and DN correctly for Ldap authentication according to my server configs.
Ldap is searching for the user, but filter is not working.

```
ldap_tools:
    domains:
       example:
            # The LDAP FQDN is required
            domain_name: test.br
            # The username to use for the LDAP connection
            username: d00021
            # The password to use for the username
            password: "test"
            # The base DN for LDAP searches (queried from the RootDSE if not provided)
            base_dn: "dc=test,dc=br"
            # The LDAP servers to use for the connection (Queried from DNS if not provided)
            servers: ["test"]        
    security:
        # Set to null for no role to be assigned by default. Or set it to another role altogether.
        roles:
            # Using the common group name
            ROLE_USER: [ 'CN=ADMINISTRADORES,OU=Grupos Administrativos,OU=Departamento de Tecnologia,DC=test,DC=br' ] 
```

```
security:
    hide_user_not_found:  true
    encoders:
        # This is the default user class returned from the LDAP provider below
        LdapTools\Bundle\LdapToolsBundle\Security\User\LdapUser: plaintext
        
    providers:
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            anonymous: ~
            # Use the default LDAP user provider defined above
            provider: ldap
            form_login:
                login_path: login
                check_path: login_check
            pattern: ^/
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
                    
        login:
            pattern: ^/login$
            anonymous: ~
            
        default:
            anonymous: ~
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
```

Help, please!

**Comment by ChadSikorra** [comment]
Is there anything but listed in the symfony log file during authentication? Also, do you know if you use AD or OpenLDAP?

**Comment by fabsnvs** [comment]
Hello there! It is AD server and that is my log file.

Filter: (&(&(objectCategory=person)(objectClass=user))(&(objectGuid=\ae\ad\79\20\0f\f4\3e\45\92\6d\d3\1e\f7\56\35\05)))
Base DN: dc=test,dc=br
Attributes: sAMAccountName,lockoutTime,accountExpires,userAccountControl,pwdLastSet,memberOf,objectGuid,sAMAccountName
Scope: subtree
Use Paging: true
Page Size: 1000
Size Limit: 0
Server: XXX
Controls: array ( )

Filter: (&(|(objectClass=group)(objectClass=contact)(objectCategory=person)(objectCategory=computer))(|(objectGuid=\ae\ad\79\20\0f\f4\3e\45\92\6d\d3\1e\f7\56\35\05)(sAMAccountName=2079adae-f40f-453e-926d-XXXXXXXX)))
Base DN: dc=test,dc=br
Attributes: dn
Scope: subtree
Use Paging: true
Page Size: 1000
Size Limit: 0
Server: XXXX
Controls: array ( )

And I think that is the return:
Filter: (&(objectClass=group)(&(member:1.2.840.113556.1.4.XXXX:=CN=xxx xxxx xxxxx xxxx ,OU=XX,OU=DesenvolvimentoDeSistemas,OU=Departamento de Tecnologia,DC=test,DC=br)))
Base DN: dc=test,dc=br
Attributes: cn
Scope: subtree
Use Paging: true
Page Size: 1000
Size Limit: 0
Server: XXXXX
Controls: array ( )

**Comment by ChadSikorra** [comment]
Are you on the version 0.1.0 of this library? I can see in the last filter it's only pulling the `cn` attribute for the groups. However, in the master branch it pulls `cn`,`objectGuid`, and  `objectSid`. Mapping a group role to a DN is a feature currently on the master branch. You could do:

`ROLE_USER: 'ADMINISTRADORES'`

...for the time being. I will be tagging a new version very shortly. I want to first tag a new version on the ldaptools/ldaptools library.

**Comment by fabsnvs** [comment]
Hello again bro! Thanks for trying to help!
I am currently using version ^0.2.0. But for now, the solution you propose didn't work. I am trying to debug my project and ldaptools vendors. 
I was talking to the person whom is responsible for the AD server, and he told this assigned roles is not working (ROLE_USER: 'ADMINISTRADORES'), and the problem is because the scope is searching for subtrees, according to the logs.

**Comment by ChadSikorra** [comment]
Scope subtree will search for anything from the point of the BaseDN (or whatever you have defined for it) onwards. It's basically like a recursive directory search.  You could temporarily try from "dev-master" instead of 0.2.0. Then you could try using the group's DN to see if that makes any difference. But I don't see any reason why the group name itself wouldn't work :/

**Comment by fabsnvs** [comment]
Bro! Problem solved!
I think ROLE_USER is a default role, and don't matter what group the user is, this rule will be assigned. 
Then, I tried while debugging "ROLE_ADMIN: 'ADMINISTRADORES' " and the user was assigned with ROLE_USER and ROLE_ADMIN. So, it worked!
Thank you very much!!!

**Comment by ChadSikorra** [comment]
Glad you figured it out! Apparently I did not have enough coffee this morning to figure that out. I have a small blurb about that behavior here in the docs:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#mapping-ldap-groups-to-roles

By default the `ROLE_USER` is assigned to any user that successfully authenticates. To change that you can set this setting:

```
# app/config/config.yml
# ...
ldap_tools:
    security:
        # Set to null for no role to be assigned by default. Or set it to another role altogether.
        default_role: ROLE_APP_USER
```
