### ISSUE TITLE
use http_basic login

### ISSUE THREAD

**Issue by hlb-schmidt** [ldaptools/ldaptools-bundle#25]
how can we use http_basic for https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Save-LDAP-Users-to-the-Database-After-Login.md ?

for example like http://symfony.com/doc/current/security/ldap.html#configuration-example-for-http-basic can

**Comment by ChadSikorra** [comment]
I think you could modify the firewall to be:

```yaml
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            http_basic:
                provider: ldap
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
```

Though I have not tested that yet.
