### ISSUE TITLE
Loading custom schema files.

### ISSUE THREAD

**Issue by TomSchillemans** [ldaptools/ldaptools-bundle#27]
I have a bundle the "AuthenticationBundle" in where I have required ldaptools and ldaptools-bundle.
This AuthenticationBundle I include itself in a bigger project. I have my ldap config inside the AuthenticationBundle and that config I include in my bigger project. 

In my custom schema I defined a ldap_user type but when I use the ldapmanager to query ldap it shows up as type user inside a dump.

![phpstorm64_2017-09-21_09-16-00](https://user-images.githubusercontent.com/3533733/30683379-876fb78a-9ead-11e7-80c4-a45f92f17592.png)

![postman_2017-09-21_09-13-39](https://user-images.githubusercontent.com/3533733/30683313-3ff02822-9ead-11e7-8b33-5250ddb821f7.png)

Does this mean it didn't load the schema file?

An additional question I have is:
I have specified which User object to use (I have a custom one inplementing the proper `LdapUserInterface` but that config is under the `security`  section. Does this mean this only takes effect when you have ldaptools do the full user authentication?

**Comment by TomSchillemans** [comment]
My query is the following.
```php
$query = $this->manager->buildLdapQuery();

$ldapObject = $query
    ->select('*')
    ->where(['objectClass' => 'inetOrgPerson'])
    ->andWhere(['cn' => $username])
    ->setScopeSubTree()
    ->setBaseDn($this->baseDn)
    ->getLdapQuery()
    ->getOneOrNullResult();
```

I haven't tried putting the `from()` call into the mix yet. I'll try that monday.


The following is the config:
```yml
ldap_tools:
  security:
    user: HeinenoordAssuradeuren\AuthenticationBundle\Entity\User
    login_query_attribute: cn
    ldap_object_type: ldap_user
```

And here is the relevant portion of my schema:
```yml
extends_default: openldap
objects:
  ldap_user:
    extends_default: ['openldap', 'user']
    type: ldap_user
```

So i am guessing this should work going by your explaination.
If this indeed should work then I'll try providing the `from()` method.

So just for verification.
Should the query return an instance of my own user (it does implement the interface you mentioned)
once I call `getOneResult()` (or equivalent like I am using)?
Or do I have to do something different to have it return my own user object?

**Comment by ChadSikorra** [comment]
Yeah, you'll want your query to reference your custom type using the from method. Any schema type in LdapTools can be referenced in the from method like that:

```yaml
$query = $this->manager->buildLdapQuery();

$ldapObject = $query
    ->select('*')
    ->from('ldap_user')
    ->where(['name' => $username])
    ->setScopeSubTree()
    ->setBaseDn($this->baseDn)
    ->getLdapQuery()
    ->getOneOrNullResult();
```

You also need to make sure to reference your custom schema in your Symfony config:

```yaml
ldap_tools:
    general:
        schema_folder: "%kernel.root_dir%/Resources/schema"
```
