### ISSUE TITLE
Role map added after user persisted.

### ISSUE THREAD

**Issue by mcgoode** [ldaptools/ldaptools-bundle#33]
I have noticed that after a user is persisted to the database and I add a new role mapping with an AD group it does not update the user upon next login, however if the user is new it does. So my guess is that is intended and I need to check groups to roles that during the authentication process?

Example process:

1.  User "user1" logs in, they get saved to the database with the current AD group to role as defined in the config.yml

User1 is in the App_admin, Human Resources, and Quality Assurance groups in AD.
```
security:
        user: AppBundle\Entity\User # added to show we are using the new user provider
        roles:
            APP_ADMIN: ['App_Admin']
            HUMAN_RESOURCES: ["Human Resources"]
```

2. Update the config.yml to include a new mapping for Quality Assurance
```
security:
        user: AppBundle\Entity\User # added to show we are using the new user provider
        roles:
            APP_ADMIN: ['App_Admin']
            HUMAN_RESOURCES: ["Human Resources"]
            QUALITY_ASSURANCE: ["Quality Assurance"]
```

3. User1 logs in again, does not pick up the new QA role in symfony.

I am persisting roles in the database and the LdapMemberships. Forgive me as I am still somewhat green with Symfony.
