### ISSUE TITLE
Symfony 4

### ISSUE THREAD

**Issue by Xeyos88** [ldaptools/ldaptools-bundle#39]
Does it work with Symfony 4?

**Comment by ChadSikorra** [comment]
The TraveCI and AppVeyor build for Symfony 4 works. However, I have not updated any of my projects to Symfony 4 yet (only 3.4). I can test sometime this week to let you know.

**Comment by ipesanz** [comment]
Hello,

with an ldap_tools.yaml file and the following content:
```
ldap_tools:
    # Setup your domain like usual...
    domains:
        example:
            domain_name: example.local
            servers: [ dc1.example.local ]
            use_tls: true
    # Tell it you want the guard to do HTTP Basic auth...
    security:
        guard:
            http_basic: true
```
It doesn't work, with the following exception:

[[Thu Feb  8 07:11:15 2018] 127.0.0.1:60898 [500]: /admin/ - Uncaught RuntimeException: Your configuration must have at least one domain. in /home/ipesanz/easy-admin-demo/vendor/ldaptools/ldaptools/src/LdapTools/LdapManager.php:86
Stack trace:
#0 /home/ipesanz/easy-admin-demo/var/cache/dev/srcDevProjectContainer.php(507): LdapTools\LdapManager->__construct(Object(LdapTools\Configuration))
#1 /home/ipesanz/easy-admin-demo/vendor/symfony/dependency-injection/Container.php(335): srcDevProjectContainer->getLdapTools_LdapManagerService()
#2 /home/ipesanz/easy-admin-demo/var/cache/dev/srcDevProjectContainer.php(2865): Symfony\Component\DependencyInjection\Container->get('LdapTools\\LdapM...')
#3 /home/ipesanz/easy-admin-demo/vendor/symfony/dependency-injection/Container.php(335): srcDevProjectContainer->getProfilerService()
#4 /home/ipesanz/easy-admin-demo/var/cache/dev/srcDevProjectContainer.php(2878): Symfony\Component\DependencyInjection\Container->get('profiler')
#5 /home/ipesanz/easy-admin-demo/vendor/symfony/dependency-injection/Container.php(335): srcDevProjectContain in /home/ipesanz/easy-admin-demo/vendor/ldaptools/ldaptools/src/LdapTools/LdapManager.php on line 86](url)

Bug or not?
