### ISSUE TITLE
It does not work Remember me

### ISSUE THREAD

**Issue by cesarluna** [ldaptools/ldaptools-bundle#54]
Configure my
config.yml
```
ldap_tools:
    general:
        default_domain: "%ldap_default_domain%"
    domains:
        EXAMPLE.LOCAL:
            domain_name: "%ldap_domain_name%"
            base_dn: "%ldap_base_dn%"
            username: "%ldap_username%"
            password: "%ldap_password%"
            servers: "%ldap_servers%"
    security:
        guard:
            default_target_path: '/'
            remember_me: true
        refresh_user_attributes: true
        # Set this to true if you want user roles re-queried on each request.
        refresh_user_roles: true
        role_attributes:
            name: name
            sid: sid
            guid: guid
            members: members
````
my Security.yml:
```
security:
    hide_user_not_found: false
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN:   ROLE_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
                always_use_default_target_path: true

            logout:       true
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 31536000 UN ANIO POR DEFECTO
                path:     /

            user_checker: app.user_checker
```
By not run remember me
