### ISSUE TITLE
Mapping LDAP Groups to Roles not working

### ISSUE THREAD

**Issue by ladenise** [ldaptools/ldaptools-bundle#8]
Hello,

Firstly, good work on making LDAP auth simple.

But I can't figure out how to map LDAP Groups to Roles.
I configured ldaptools-bundle this way:
```
ldap_tools:
    security:
        default_role: null
        roles:
            ROLE_ADMIN: "CN=group 1,OU=groups_l,OU=lorem,OU=Ipsum,DC=dolor,DC=local"
            ROLE_USER: "CN=group 2,OU=groups_l,OU=lorem,OU=Ipsum,DC=dolor,DC=local"
```
I manage to login successfully but can't map the good roles.
Do you have any idea what I'm doing wrong?
