### ISSUE TITLE
cannot inject ldap manager into event subscriber

### ISSUE THREAD

**Issue by markusu49** [ldaptools/ldaptools-bundle#9]
Injecting the ldap manager into an event subscriber throws a ServiceCircularReferenceException.

A similar problem is described here: http://stackoverflow.com/q/7561013

The solution seems to be not so simple and involve design considerations. The only workaround is to inject the whole service container.

**Comment by ChadSikorra** [comment]
This appears to be because the event dispatcher is involved in the instantiation of the main LdapTools configuration class, then the LdapManager requires that configuration, and in the compiler passes I'm adding method calls to the event dispatcher for the tagged events. But obviously if one of those tagged events requires the LdapManager, it will become circular.

I'm wondering if marking the service as [lazy](symfony.com/doc/current/service_container/lazy_services.html) would get around this?

**Comment by markusu49** [comment]
Just tried it out... Neither marking the event subscriber nor the ldap manager as lazy makes any difference.

**Comment by ChadSikorra** [comment]
Even after deleting the cache? Ugh. I'll have to mess with this over the weekend a bit.

**Comment by ChadSikorra** [comment]
Setting the listener/subscriber service to lazy does work, I just tested it. Make sure to clear your cache first and install the needed dependencies:

`composer require ocramius/proxy-manager`

Listener Class:

```php
namespace AppBundle\Event;

use LdapTools\Event\LdapOperationEvent;
use LdapTools\LdapManager;

class LdapEventListener
{
    protected $ldap;

    public function __construct(LdapManager $ldap)
    {
        $this->ldap = $ldap;
    }

    public function beforeOperation(LdapOperationEvent $event)
    {
        dump($event->getOperation()->getName());
    }
}
```

Service definition:

```yaml
services:
    app_bundle.event.ldap_listener:
        class: AppBundle\Event\LdapEventListener
        lazy: true
        arguments: ['@ldap_tools.ldap_manager']
        tags:
            - { name: 'ldap_tools.event_listener', event: 'ldap.operation.execute.before', method: beforeOperation }
```

Clear and Warmup the cache:

`php app/bin cache:clear`
`php app/bin cache:warmup --env=dev`
